sue445/ccc_privacy_crawler

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6000582627907563536">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150503105320

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6003119344355256391">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150510105322

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6005656059060927642">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150517105325

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6010729489284509175">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150531105317

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6013266202763385332">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150607105319

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6033596884629854745">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6033596884629854745">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150802132024

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6046280436028200914">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6046280436028200914">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150906132016

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6064037462554308297">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6064037462554308297">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151025132010

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6069110897452904797">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6069110897452904797">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151108132014

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6076721038714505916">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6076721038714505916">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151129132019

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6084331184242795407">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6084331184242795407">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151220132030

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6086867900234673994">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6086867900234673994">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151227132022

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6091941328435438880">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6091941328435438880">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160110132037

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6102088191624384457">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6102088191624384457">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160207132058

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6112235048897981292">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6112235048897981292">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160306132106

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6124918624744950535">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6124918624744950535">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160410132059

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6129992058420043916">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6129992058420043916">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160424132056

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6135065485896179300">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6135065485896179300">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160508132146

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6150285776522449694">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6150285776522449694">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160619132132

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6152822492608396018">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6152822492608396018">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160626132215

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6165506068471787705">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6165506068471787705">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160731132011

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6168042783787075640">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6168042783787075640">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160807132016

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6170579498118502307">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6170579498118502307">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160814132015

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6173116210216291431">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6173116210216291431">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160821132022

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6180726357997087809">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6180726357997087809">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160911132036

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6185799787336557700">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6185799787336557700">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160925132026

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6195946646525317362">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6195946646525317362">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161023132038

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6198483361317065192">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6198483361317065192">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161030132027

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6218777084683647412">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6218777084683647412">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161225132128

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6221313797335409690">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6221313797335409690">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170101132008

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6239070801914506029">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6239070801914506029">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170219132006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6244144232734407149">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6244144232734407149">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170305132007

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6246680949471692614">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6246680949471692614">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170312132006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6256827809585586833">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6256827809585586833">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170409132004

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6261901240590051947">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6261901240590051947">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170423132006

---

Gemfile
Gemfile.lock

v0.14.0.2 is broken
ttps://github.com/padrino/padrino-framework/pull/2133

Keep padrino v0.14.0.1

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6272048100475515714">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6272048100475515714">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170521132005

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6274584815227565234">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6274584815227565234">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170528132007

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6277121532824799012">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6277121532824799012">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170604132006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6282194957845523204">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6282194957845523204">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170618132006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6287268387828024031">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6287268387828024031">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170702132005

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6294878536898567306">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6294878536898567306">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170723132005

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6299951963862128454">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6299951963862128454">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170806132006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6305025393738950683">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6305025393738950683">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170820132006

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6321049396160094745">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6321049396160094745">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171003183345

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6323586111502651831">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6323586111502651831">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171010183345

---

Gemfile
Gemfile.lock
spec/factories/companies.rb
spec/factories/sequences.rb
spec/spec_helper.rb

Migrate to factory_bot

---

Gemfile
Gemfile.lock

Use pry-byebug instead of pry-nav

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6331196256275087898">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6331196256275087898">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171031183345

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6341343112396621142">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6341343112396621142">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171128183344

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6343879828110666409">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6343879828110666409">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171205183344

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6346416538574646706">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6346416538574646706">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20171212183343

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6361636834242517824">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6361636834242517824">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180123183344

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6395406266896437085">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6395406266896437085">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180426230124

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6397941722856565646">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6397941722856565646">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180503225623

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6400478438853148807">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6400478438853148807">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180510225624

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6403015158241386577">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6403015158241386577">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180517225625

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6410625301769422498">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6410625301769422498">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180607225625

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6413745185215515026">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6413745185215515026">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180616133344

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6421355328931032937">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6421355328931032937">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180707133342

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6426428759478891800">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6426428759478891800">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180721133343

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6431502189686518355">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6431502189686518355">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180804133343

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6439112339966695896">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6439112339966695896">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180825133344

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6451795907300345478">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6451795907300345478">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20180929133343

---

.circleci/config.yml

Reverts sue445/ccc_privacy_crawler#672

Revert "Upgrade to latest heroku orb"

---

lib/workers/pdf_crawl_worker.rb
models/company.rb

Migrate to new download url
